Create/human scoring/scorer entity
sirpa44/human_scoring pull request #1
Opened 2019-02-25 09:36 UTC by sirpa44

2019-03-01 18:21 UTC, gyszucs requested changes
- use PHP 7.2 in composer 
- add some basic instructions in README.md about installation and configuration at least. Later you can extend it with some description about each feature.
- It would be nice to put `declare(strict_types = 1);` in each PHP file and start using PHP 7 type hinting everywhere.

2019-03-01 18:21 UTC, gyszucs commented on src/Entity/ScorerEntity.php
> +class ScorerEntity implements UserInterface
Please, don't use `Entity` in the class name, it is not necessary.

2019-03-01 18:21 UTC, gyszucs commented on config/service_test.yaml
> +  App\DataFixtures\ScorerFixture:
You don't have to declare the fixture as service manually because it is already done by Symfony automatically. You can remove this line and much probably the entire file also.

2019-03-01 18:21 UTC, gyszucs commented on src/Controller/HomeController.php
> +        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
This is unnecessary if you use `access_control` in `security.yaml` and ROLE attributes in the user entity properly. See the other comments. Once you made the changes in there, you can remove this `if` case and the `$urlGenerator` service. Symfony will redirect the user to the login page automatically if the authentication fails.

2019-03-01 18:21 UTC, gyszucs commented on src/Entity/ScorerEntity.php
> +    public function getRoles():array
Please use the following logic to handle roles: https://symfony.com/doc/current/security.html#roles. The important thing is to always have at least `ROLE_USER` so you can leverage the `access_control` in `security.yaml`.

2019-03-01 18:21 UTC, gyszucs commented on config/packages/security.yaml
> +#         - { path: ^/, roles: Scorer }
Please uncomment this line and use `roles: ROLE_USER` instead of `roles: Scorer`. This way is much easier to secure the entire application.

2019-03-01 18:21 UTC, gyszucs commented on src/Controller/HomeController.php
> +        $user = $this->security->getUser();
You don't have use `Security` service here to get the user because you already using `AbstractController` which has a nice method to fetch the user which is `$this->getUser();`, so you can remove the injected service.

2019-03-01 18:21 UTC, gyszucs commented on src/Controller/HomeController.php
> +/**
Please remove this doc block from the beginning of each PHP file. Probably it was added by PhpStorm so make sure it is disabled. I guess in the final version we will have a different text as licence here.

2019-03-01 18:21 UTC, gyszucs commented on src/Entity/ScorerEntity.php
> +     * @return array (Role|string)[] The user roles
The proper PhpDoc for this case is `string[]`. It means the result is an array containing only strings.

2019-03-01 18:21 UTC, gyszucs commented on tests/Integration/Controller/SecurityControllerTest.php
> +    public function testLoginWithLastUserName()
Test is failing: `ArgumentCountError: Too few arguments to function App\DataFixtures\ScorerFixture::__construct(), 0 passed in /home/gyula/Projects/human_scoring/tests/Integration/Controller/SecurityControllerTest.php on line 14 and exactly 1 expected`

2019-03-06 14:23 UTC, ekkinox commented on src/Controller/HomeController.php
> +        $user = $this->security->getUser();
NOTE: You can also simply inject `UserInterface`, on autowiring it'll give you current user

2019-03-11 13:29 UTC, merged